import{S as f,i as a}from"./assets/vendor-Fc49kKW1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const p="46037450-a04b7b74a12a46e49ae394c24",y="https://pixabay.com/api/";function d(i){return fetch(`${y}?key=${p}&q=${i}&image_type=photo&orientation=horizontal&safesearch=true`).then(t=>{if(!t.ok)throw new Error("Sorry, there are no images matching your search query. Please try again!");return t.json()})}const l=document.querySelector(".js-gallery");function g(i){l.innerHTML="";const t=i.hits.map(({webformatURL:n,largeImageURL:o,tags:e,likes:r,views:s,comments:u,downloads:m})=>`
      <a href="${o}" class="gallery-item">
        <img src="${n}" alt="${e}" loading="lazy" />
        <ul class="info">
          <li><p>Likes</p> ${r}</li>
          <li><p>Views</p> ${s}</li>
          <li><p>Comments</p> ${u}</li>
          <li><p>Downloads</p> ${m}</li>
        </ul>
      </a>
    `).join("");l.insertAdjacentHTML("beforeend",t)}const h=document.querySelector(".js-search-form"),c=document.getElementById("loader"),b=document.querySelector(".gallery");let L=new f(".gallery-item",{captionsData:"alt",captionDelay:250});h.addEventListener("submit",$);function $(i){i.preventDefault();const t=i.currentTarget,{query:n}=t.elements;if(n.value.trim()===""){a.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}c.style.display="block",b.innerHTML="",d(n.value).then(o=>{if(o.hits.length===0){a.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(o),L.refresh()}).catch(o=>{a.error({title:"Error",message:o.message,position:"topRight"})}).finally(()=>{t.reset(),c.style.display="none"})}
//# sourceMappingURL=index.js.map
